remote: true

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  director: true
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Identity Access Management
  - IAM

locations:
  - United States
  - United Arab Emirates
  - Canada
  - Luxenbourg

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
